usersservice:
  ldap:
    uri: "ldap://ldap-openldap"
    dn: "cn=admin,dc=example,dc=com"
    password:
      password: pass123
webui:
  endpoints:
    authendpoint:
      url: https://auth.__DOMAIN__/dex
      secret: Yp4fGf79FutdBDJArQqxhUiVbufVxjzu
gateway:
  endpoints:
    authendpoint: "https://auth.__DOMAIN__/dex"
    usersservice: "http://test-controller-usersservice:5000/users/"
    appsservice: "http://test-appsservice:5000"
appsservice:
  enabled: false

adminPassword:
  password: "pass123"
configAdminPassword:
  password: "pass123"
initialDB:
  serviceaccounts:
  - name: dex
    password: dex123
