apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: appsservice
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GIT_REPO
              value: {{ .Values.git_repo.url }}
{{- if .Values.git_repo.subpath }}
            - name: GIT_SUBPATH
              value: {{ .Values.git_repo.subpath }}
{{- end }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: sshkey
              mountPath: "/app/sshkey"
              readOnly: true
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http

      volumes:
      - name: sshkey
        secret:
{{- if .Values.git_repo.sshkey.secret.name }}
          secretName: {{ .Values.git_repo.sshkey.secret.name }}
          items:
            - key: {{ .Values.git_repo.sshkey.secret.key }}
              path: id_rsa
{{- else }}
          secretName: {{ include "chart.fullname" . }}-sshkey
          items:
            - key: ssh-privatekey
              path: id_rsa
{{- end }}
          defaultMode: 0400
