apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      component: appsservice
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        component: appsservice
    spec:
      initContainers:
        - name: git-waiter
          image: alpine
          command: ["/bin/sh"]
          args: ["-c", "echo 'waiting for /app/workdir/.git to appear'; until [ -d /app/workdir/.git ]; do echo -n '.'; sleep 1; done"]
          volumeMounts:
            - name: git
              mountPath: "/app/workdir"
      containers:
        - name: appsservice
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: USERS_DOMAIN
              value: {{ .Values.users_domain }}
            - name: AUTHSERVICE_ENDPOINT
              value: {{ .Values.authservice_endpoint }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          volumeMounts:
            - name: git
              mountPath: /app/workdir
      volumes:
        - name: git
          persistentVolumeClaim:
            claimName: {{ include "chart.fullname" . }}-git
