apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.exphost.pl
spec:
  group: exphost.pl
  names:
    kind: Application
    plural: applications
    singular: application
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                config:
                  type: object
                components:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      helm:
                        type: object
                        properties:
                          type:
                            type: string
                          chart:
                            type: object
                            properties:
                              name:
                                type: string
                              repository:
                                type: string
                              version:
                                type: string
                      dockerfile:
                        type: object
                        properties:
                          type:
                            type: string
                      config:
                        type: object
      additionalPrinterColumns:
        - name: App
          type: string
          jsonPath: .metadata.labels.app
        - name: Org
          type: string
          jsonPath: .metadata.labels.org
        - name: Version
          type: string
          jsonPath: .metadata.labels.version
  scope: Namespaced
